INSERT INTO work_type (id, name) VALUES (1, 'Foundation Laying');
INSERT INTO work_type (id, name) VALUES (2, 'Framework Installation');
INSERT INTO work_type (id, name) VALUES (3, 'Electrical Fittings');
INSERT INTO work_type (id, name) VALUES (4, 'Plumbing Installation');
INSERT INTO work_type (id, name) VALUES (5, 'Roofing');
INSERT INTO work_type (id, name) VALUES (6, 'Insulation Work');
INSERT INTO work_type (id, name) VALUES (7, 'Window Installation');
INSERT INTO work_type (id, name) VALUES (8, 'Flooring');
INSERT INTO work_type (id, name) VALUES (9, 'Painting and Decoration');
INSERT INTO work_type (id, name) VALUES (10, 'Landscaping');
INSERT INTO work_type (id, name) VALUES (11, 'HVAC Installation');
INSERT INTO work_type (id, name) VALUES (12, 'Exterior Cladding');
INSERT INTO work_type (id, name) VALUES (13, 'Interior Design');
INSERT INTO work_type (id, name) VALUES (14, 'Security Systems Installation');
INSERT INTO work_type (id, name) VALUES (15, 'Fire Protection Systems');
INSERT INTO work_type (id, name) VALUES (16, 'Waterproofing');
INSERT INTO work_type (id, name) VALUES (17, 'Masonry Work');
INSERT INTO work_type (id, name) VALUES (18, 'Carpentry');
INSERT INTO work_type (id, name) VALUES (19, 'Tiling');
INSERT INTO work_type (id, name) VALUES (20, 'Concrete Forming');
