spring:
  application:
    name: service
  datasource:
    url: jdbc:postgresql://${CONSTRUCTION_SYSTEM_MS_SERVICE_DB_URL}
    username: ${CONSTRUCTION_SYSTEM_POSTGRES_USER}
    password: ${CONSTRUCTION_SYSTEM_POSTGRES_PASSWORD}
  graphql:
    graphiql:
      enabled: true
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    d.zhdanov.ccfit.nsu: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
