server:
  port: 8081

spring:
  application:
    name: service

  datasource:
    url: ${CONSTRUCTION_SYSTEM_MS_SERVICE_DB_URL}
    username: ${CONSTRUCTION_SYSTEM_POSTGRES_USER}
    password: ${CONSTRUCTION_SYSTEM_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  graphql:
    graphiql:
      enabled: true

management:
  tracing:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.jdbc: TRACE
    org.springframework.security: TRACE
    d.zhdanov.ccfit.nsu.config.HeaderAuthFilter: DEBUG
    com.netflix.graphql.dgs: DEBUG
    org.springframework.graphql: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%level] - %msg%n"