app:
  config:
    login-uri: ${KEYCLOAK_REGISTRATION_URI}

server:
  port: 8081

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    d.zhdanov.ccfit.nsu: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

spring:
  application:
    name: gateway

  cloud:
    gateway:
      global cors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: authorized
          uri: http://localhost:8082
          predicates:
            - Path=/authorized/**
          filters:
            - UserInfoHeaderFactory
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_SET_URI}
management:
  tracing:
    enabled: true
