server:
  port: 8080

logging:
  level:
    #    root: INFO
    #    d.zhdanov.ccfit.nsu: DEBUG
    #    org.springframework.web: DEBUG
    org.springframework.web: TRACE
    org.springframework.security: TRACE
  #    reactor.netty.http.server: DEBUG
  #    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.filter.UserInfoHeaderFactory: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

spring:
  application:
    name: gateway
  cloud:
    gateway:
      global cors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - authorization
              - content-type
              - x-requested-with
            exposedHeaders:
              - authorization
            allow-credentials: true

      routes:
        - id: api
          uri: http://localhost:8081
          predicates:
            - Path=/graphql
          filters:
            - UserInfoHeaderFactory
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_SET_URI}

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health
#  tracing:
#    enabled: true
#    sampling:
#      probability: 1.0
#    propagation:
#      produce: W3C
#  otlp:
#    tracing:
#      endpoint: http://localhost:4318/v1/traces
#
#otel:
#  service:
#    name: ${spring.application.name}
