spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: keycloak-route
          uri: lb://keycloak
          predicates:
            - Path=/keycloak/**
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway-client        # Ваш Client ID из Keycloak
            client-secret: { your-client-secret }  # Ваш Client Secret
            authorization-grant-type: authorization_code
            scope: openid

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    d.zhdanov.ccfit.nsu: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

server:
  port: 8080  # Gateway работает на этом порту
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
