server:
  port: 8080

logging:
  level:
#    root: INFO
#    d.zhdanov.ccfit.nsu: DEBUG
#    org.springframework.web: DEBUG
    org.springframework.web: TRACE
    org.springframework.security: TRACE
#    reactor.netty.http.server: DEBUG
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

spring:
  application:
    name: gateway
  cloud:
    gateway:
      global cors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - authorization
              - content-type
              - x-requested-with
            exposedHeaders:
              - authorization
            allow-credentials: true

      routes:
        - id: api
          uri: http://localhost:8081
          predicates:
            - Path=/graphql
          filters:
            - UserInfoHeaderFactory
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_SET_URI}

management:
  tracing:
    enabled: true
