version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${CONSTRUCTION_SYSTEM_POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${CONSTRUCTION_SYSTEM_POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-construction-system}
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql  # Добавляем скрипт для инициализации базы данных
      - postgres-data-dev:/var/lib/postgresql/data
    networks:
      - dev-net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB" ]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s

  postgres-migration:
    image: liquibase/liquibase:4.27-alpine
    command:
      - --driver=org.postgresql.Driver
      - --changeLogFile=db.changelog-master.xml
      - --url=jdbc:postgresql://postgres:5432/construction-system
      - --username=${CONSTRUCTION_SYSTEM_POSTGRES_USER:-user}
      - --password=${CONSTRUCTION_SYSTEM_POSTGRES_PASSWORD:-password}
      - update
    volumes:
      - ./db/db.changelog-master.xml:/liquibase/db.changelog-master.xml
      - ./db/DDL:/liquibase/DDL
      - ./db/DML:/liquibase/DML
      - ./db/reports:/liquibase/reports
    networks:
      - dev-net
    restart: no
    depends_on:
      postgres:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command:
      - start-dev
#      - --import-realm
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-password}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-db:5432/${CONSTRUCTION_SYSTEM_POSTGRES_DB:-construction-system}
      KC_DB_USERNAME: ${CONSTRUCTION_SYSTEM_POSTGRES_USER:-user}
      KC_DB_PASSWORD: ${CONSTRUCTION_SYSTEM_POSTGRES_PASSWORD:-password}
      KC_PROXY: edge
#      JAVA_OPTS: "-Dspring.cloud.eureka.client.service-url.defaultZone=http://localhost:8761/eureka/ -Dspring.application.name=keycloak-service"
#      EUREKA_CLIENT_SERVICEURL: http://localhost:8761/eureka
      SPRING_APPLICATION_NAME: keycloak
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    networks:
      - dev-net
    depends_on:
      - postgres
#      - eureka

  eureka:
    build:
      context: ../eureka
      dockerfile: Dockerfile
    container_name: eureka
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - dev-net


volumes:
  postgres-data-dev: # Здесь добавляем определение тома postgres-data-dev
    driver: local


networks:
  dev-net:
    driver: bridge
